variables:
  GIT_DEPTH: "3"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - yum update -y
  - echo "Hello CI"
  - export PATH=$PATH:/usr/local/bin:/usr/bin
  - source setup_env.sh

install_dependencies:
  when:
    manual
  script:
    - $(pwd)
    - if [ "${BUILD_DEPS}" == "1"]; then source setup_env tools;
    - if [ "${BUILD_ROMS}" == "1"]; then source setup_env roms;

pass-job:
  script:
    - echo "Passing job 1"
    - exit 0

fail-job:
  script:
    - echo "Failing job 2"
    - exit 1 

