variables:
  CI_PROJECT_DIR: /builds/dpetrisko/
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: "50"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none

before_script:
  - source setup_env.sh

# Only needed if not using the provided Gitlab docker image
install_dependencies:
  when:
    manual
  script:
    - $(pwd)
    - if [ "${BUILD_DEPS}" == "1"]; then source setup_env tools;
    - if [ "${BUILD_ROMS}" == "1"]; then source setup_env roms;

pass-job:
  script:
    - echo "Passing job 1"
    - exit 0

#fail-job:
#  script:
#    - echo "Failing job 2"
#    - exit 1 

test-job:
  script:
    - cd bp_top
    - ./regress.sh verilator

