variables:
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: "50"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none

before_script:
  - echo "Hello CI"
  - export PATH=$PATH:/usr/local/bin:/usr/bin
  - source setup_env.sh

install_dependencies:
  when:
    manual
  script:
    - $(pwd)
    - if [ "${BUILD_DEPS}" == "1"]; then source setup_env tools;
    - if [ "${BUILD_ROMS}" == "1"]; then source setup_env roms;

pass-job:
  script:
    - echo "Passing job 1"
    - exit 0

fail-job:
  script:
    - echo "Failing job 2"
    - exit 1 

test-job:
  script:
    - cd bp_top
    - ./regress.sh

