variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - echo "Hello CI"
  - source setup_env.sh

pass-job:
  script:
    - echo "Passing job 1"
    - exit 0

fail-job:
  script:
    - echo "Failing job 2"
    - exit 1 

