variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - echo "Hello CI"
  - source setup_env.sh

install_dependencies:
  when:
    manual
  script:
    - if [ "${BUILD_DEPS}" == "1"]; then source setup_env tools;
    - if [ "${BUILD_ROMS}" == "1"]; then source setup_env roms;

pass-job:
  script:
    - echo "Passing job 1"
    - exit 0

fail-job:
  script:
    - echo "Failing job 2"
    - exit 1 

